In [2]:
##check numpy version

import numpy as np 
#1d,2d,3d,4d   
np.__version__


'2.3.0'

In [7]:
lst=[1,2,3,4,5]
ar1 = np.array(lst)
ar1
#print(type(ar1))

array([1, 2, 3, 4, 5])

In [16]:
lst = [1,2,"3",4,5]

ar1 = np.array(lst)
ar1

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [18]:
##when you to create an array in a range

ar1 = np.arange(1,10)
ar1


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
ar3 = np.arange(5)
ar3

array([0, 1, 2, 3, 4])

In [25]:
arr4 = np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#arr5 = np.linspace(1,10,5)  ## 1 to 10 range or kitne number chaiye 5
arr5 = np.linspace(0,20,50)
arr5

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [ ]:
##1d array
arr1 = np.arange(1,31).reshape(5,6) ##shape change kar deta hai 1d ko 2d,3d me 
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [30]:
arr2 = np.random.randint(1,120,10)  ##random numbers ki array chaiye to ek function hai random joo random integer number dega
arr2

array([  9, 114, 102,   9, 111,  29, 109,  90, 100,  97], dtype=int32)

In [ ]:
arr2 = np.random.random(70) ##float ke liye 
arr2

array([0.10190243, 0.69588961, 0.53851671, 0.82268843, 0.35869467,
       0.86082356, 0.3292395 , 0.98895657, 0.98702502, 0.28603828,
       0.90852908, 0.38934266, 0.05945961, 0.94031371, 0.3538071 ,
       0.38004962, 0.80833355, 0.28627053, 0.5805327 , 0.93954003,
       0.37149933, 0.12754894, 0.10468075, 0.79987369, 0.98971519,
       0.7813667 , 0.24298145, 0.10491217, 0.66043914, 0.57648818,
       0.26330232, 0.70905734, 0.77349619, 0.03958222, 0.07847519,
       0.14129751, 0.22145042, 0.47190354, 0.38466563, 0.34011008,
       0.16083467, 0.69316971, 0.980441  , 0.3800569 , 0.06497858,
       0.14094031, 0.48647772, 0.53392043, 0.33356206, 0.53277901,
       0.21167523, 0.31887528, 0.12283754, 0.01826591, 0.3708979 ,
       0.68967802, 0.57894925, 0.35204761, 0.46240005, 0.40564426,
       0.38584092, 0.07278574, 0.05385637, 0.39095224, 0.35900138,
       0.36521148, 0.20326247, 0.66490783, 0.35660512, 0.01554032])

In [ ]:
##2d array
arr2 = np.arange(60).reshape((12,5))  ##rows and column
arr2.shape
arr2.dtype  ##data type
arr2.size
arr2.ndim ##n dimension 

2

In [48]:
##multi dimension array ko conert karte hai 1d me 
arr2.ravel()
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [51]:
arr8 = np.arange(60).reshape((12,5))
print(arr8.shape)

arr9 = arr8.T.shape
arr9



(12, 5)


(5, 12)

In [ ]:
##Indexing and Slicing
###1D Array
##slicing
arr1 = np.arange(1,10)[1:5]
print(arr1)

##indexing


In [94]:
##2D Array 
arr10 = np.arange(1,61).reshape(15,4)
arr10

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60]])

In [ ]:
###3D Array
arr11 = np.arange(225).reshape(3,15,5)  ##3=table,15=rows,5=column
arr11

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [ ]:
# Create a 3D numpy array with elements from 'a' to 'z'
arr12 = np.array(list('abcdefghijklmnopqrstuvwxyz')).reshape(2, 13, 2)
arr12

array([[['a'],
        ['b'],
        ['c'],
        ['d'],
        ['e'],
        ['f'],
        ['g'],
        ['h'],
        ['i'],
        ['j'],
        ['k'],
        ['l'],
        ['m']],

       [['n'],
        ['o'],
        ['p'],
        ['q'],
        ['r'],
        ['s'],
        ['t'],
        ['u'],
        ['v'],
        ['w'],
        ['x'],
        ['y'],
        ['z']]], dtype='<U1')

In [ ]:
##slicing in 3D Array
##[table start : table end : table skip, row start : row end : row skip, col start : col end : col skip]

In [133]:
np.max(arr8)
np.min(arr8)
np.sum(arr8)
np.mean(arr8)
np.median(arr8)
np.std(arr8)


np.float64(17.318102282486574)

In [134]:
arr8.sort()

In [ ]:
arr13 = np.array([2,5,1,9])   
arr13.argsort() ####index number ko sort karta hai return sorted index

array([2, 0, 1, 3])

In [137]:
arr11*2

array([4, 6, 8])

In [141]:
##lst - 
## arr14 = np.array([1,2,"3",4,5])
ar14 = np.array([1,2,3,4,5],ndmin=6)
ar14

array([[[[[[1, 2, 3, 4, 5]]]]]])